/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // MD3 Color Tokens (from stitch designs)
        'primary':                  '#006d36',
        'on-primary':               '#ffffff',
        'primary-container':        '#50c878',
        'on-primary-container':     '#005025',
        'primary-fixed':            '#83fba5',
        'primary-fixed-dim':        '#66dd8b',
        'on-primary-fixed':         '#00210c',
        'on-primary-fixed-variant': '#005227',
        'secondary':                '#50606f',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#d1e1f4',
        'on-secondary-container':   '#556474',
        'secondary-fixed':          '#d4e4f6',
        'secondary-fixed-dim':      '#b8c8da',
        'on-secondary-fixed':       '#0d1d2a',
        'on-secondary-fixed-variant': '#394857',
        'tertiary':                 '#99443a',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       '#ff9587',
        'on-tertiary-container':    '#782b23',
        'tertiary-fixed':           '#ffdad5',
        'tertiary-fixed-dim':       '#ffb4a9',
        'on-tertiary-fixed':        '#3f0302',
        'on-tertiary-fixed-variant': '#7b2e25',
        'error':                    '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        'on-error-container':       '#93000a',
        'surface':                  '#f8f9fa',
        'surface-dim':              '#d9dadb',
        'surface-bright':           '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f3f4f5',
        'surface-container':        '#edeeef',
        'surface-container-high':   '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant':          '#e1e3e4',
        'surface-tint':             '#006d36',
        'on-surface':               '#191c1d',
        'on-surface-variant':       '#3e4a3f',
        'outline':                  '#6e7a6e',
        'outline-variant':          '#bdcabc',
        'inverse-surface':          '#2e3132',
        'inverse-on-surface':       '#f0f1f2',
        'inverse-primary':          '#66dd8b',
        'background':               '#f8f9fa',
        'on-background':            '#191c1d',
        // Legacy tokens (kept for backward compat with any remaining usage)
        'mcd-primary':       '#0F4C5C',
        'mcd-secondary':     '#E36414',
        'mcd-success':       '#2A9D8F',
        'mcd-dark-bg':       '#0A1929',
        'mcd-dark-surface':  '#132F4C',
        'mcd-dark-border':   '#1E3A5F',
        'mcd-light-bg':      '#F8FAFC',
        'mcd-light-border':  '#E2E8F0',
      },
      fontFamily: {
        sans:     ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body:     ['Inter', 'system-ui', 'sans-serif'],
        label:    ['Inter', 'system-ui', 'sans-serif'],
        mono:     ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
      boxShadow: {
        'teal-glow':    '0 0 24px rgba(15, 76, 92, 0.5)',
        'green-glow':   '0 0 24px rgba(0, 109, 54, 0.4)',
        'card-dark':    '0 4px 24px rgba(0, 0, 0, 0.4)',
        'card-light':   '0 4px 24px rgba(15, 23, 42, 0.08)',
      },
      animation: {
        'breathe':    'breathe 3s ease-in-out infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'slide-up':   'slideUp 0.5s ease-out forwards',
        'fade-in':    'fadeIn 0.4s ease-out forwards',
        'spin-slow':  'spin 8s linear infinite',
      },
      keyframes: {
        breathe: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.8' },
          '50%':      { transform: 'scale(1.15)', opacity: '1' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}

